### ISSUE TITLE
RMG tool generatefluxdiagram got ZeroDivisionError: float division

### ISSUE THREAD

**Issue by shenghuiqin** [ReactionMechanismGenerator/RMG-website#180]
hi guys, I met this error when using generateFluxDiagram
`Traceback (most recent call last):
  File "generateFluxDiagram.py", line 139, in <module>
    main()
  File "generateFluxDiagram.py", line 136, in main
    checkDuplicates=checkDuplicates)
  File "/home/shenghuiqin/Code/RMG-Py/rmgpy/tools/fluxdiagram.py", line 603, in createFluxDiagram
    time, coreSpeciesConcentrations, coreReactionRates = simulate(rmg.reactionModel, reactionSystem, settings)
  File "/home/shenghuiqin/Code/RMG-Py/rmgpy/tools/fluxdiagram.py", line 406, in simulate
    sens_atol=simulatorSettings.sens_atol, sens_rtol=simulatorSettings.sens_rtol,conditions=None)
  File "rmgpy/solver/simple.pyx", line 166, in rmgpy.solver.simple.SimpleReactor.initializeModel
  File "rmgpy/solver/simple.pyx", line 202, in rmgpy.solver.simple.SimpleReactor.initializeModel
  File "rmgpy/solver/base.pyx", line 475, in rmgpy.solver.base.ReactionSystem.set_initial_derivative
  File "rmgpy/solver/simple.pyx", line 371, in rmgpy.solver.simple.SimpleReactor.residual
ZeroDivisionError: float division`
how to solve it?
thank you

**Comment by xiaoruiDong** [comment]
@shenghuiqin, Thanks for reporting the bug. Can you try it again with the newest RMG-website again? Previously, the website was python2 backend while I believe you were using RMG-Py3 to generate models. If it still does not work, can you provide more information on how to reproduce it? Besides, it seems to be an RMG-Py issue, since RMG-website generateFluxdiagram module just simply call the same-name module in RMG-Py. It is better to report the issue at the RMG-Py depository. Thanks!

**Comment by shenghuiqin** [comment]
@xiaoruiDong sorry, my RMG was still python 2, I guess I need update and try again.
thank you

**Comment by shenghuiqin** [comment]
I tried to run with python 3 (locally RMG), it failed with same error message above.
`
Traceback (most recent call last):
  File "//home/shenghuiqin/RMG-Py/scripts/generateFluxDiagram.py", line 141, in <module>
    main()
  File "//home/shenghuiqin/RMG-Py/scripts/generateFluxDiagram.py", line 137, in main
    diffusion_limited=dflag, check_duplicates=check_duplicates)
  File "/home/shenghuiqin/RMG-Py/rmgpy/tools/fluxdiagram.py", line 611, in create_flux_diagram
    settings)
  File "/home/shenghuiqin/RMG-Py/rmgpy/tools/fluxdiagram.py", line 411, in simulate
    conditions=None)
  File "rmgpy/solver/simple.pyx", line 183, in rmgpy.solver.simple.SimpleReactor.initialize_model
  File "rmgpy/solver/simple.pyx", line 220, in rmgpy.solver.simple.SimpleReactor.initialize_model
  File "rmgpy/solver/base.pyx", line 475, in rmgpy.solver.base.ReactionSystem.set_initial_derivative
  File "rmgpy/solver/simple.pyx", line 391, in rmgpy.solver.simple.SimpleReactor.residual
ZeroDivisionError: float division
`

besides, I ran it on RMG website, got this error,
`subprocess.CalledProcessError: Command '['python', '/var/www/RMG-Py/scripts/generateFluxDiagram.py', '/var/www/RMG-website/rmgweb/media/rmg/tools/flux/input.py', '/var/www/RMG-website/rmgweb/media/rmg/tools/flux/chem.inp', '/var/www/RMG-website/rmgweb/media/rmg/tools/flux/species_dictionary.txt', '-n', '50', '-e', '50', '-c', '1e-06', '-r', '1e-06', '-t', '1.25']' returned non-zero exit status 1.`

> @shenghuiqin, Thanks for reporting the bug. Can you try it again with the newest RMG-website again? Previously, the website was python2 backend while I believe you were using RMG-Py3 to generate models. If it still does not work, can you provide more information on how to reproduce it? Besides, it seems to be an RMG-Py issue, since RMG-website generateFluxdiagram module just simply call the same-name module in RMG-Py. It is better to report the issue at the RMG-Py depository. Thanks!
